Minor refactoring of read/write functions and primitive procs. Added functions to help store data in memcached. Fixes to HTTP support and more tests.
git-svn-id: https://svn.apache.org/repos/asf/tuscany/cpp/sca@831640 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/modules/http/httpd-test b/modules/http/httpd-test
--- a/modules/http/httpd-test
+++ b/modules/http/httpd-test
@@ -18,20 +18,59 @@
 #  under the License.
 
 echo "Testing..."
-mkdir -p tmp
-mkdir -p tmp/conf
-cp test-conf/* tmp/conf
-cat >tmp/conf/httpd.conf <<EOF
-ServerName 127.0.0.1
-Listen 9090
-DocumentRoot `pwd`/test-htdocs
+
+# Setup
+./httpd-conf tmp 8090 htdocs
+cat >>tmp/conf/httpd.conf <<EOF
+<Location /test>
+SetHandler mod_tuscany
+SCAContribution `pwd`/
+SCAComponent httpd-test
+SCAImplementation httpd-test.scm
+</Location>
 EOF
-mkdir -p tmp/logs
 apachectl -k start -d `pwd`/tmp
 sleep 1
-curl http://localhost:9090/index.html 2>&1 | grep "It works" >/dev/null
+
+# Test HTTP GET
+curl http://localhost:8090/index.html 2>/dev/null >tmp/index.html
+diff tmp/index.html htdocs/index.html
 rc=$?
+
+# Test ATOMPub
+if [ "$rc" = "0" ]; then
+    curl http://localhost:8090/test/ >tmp/feed.xml 2>/dev/null
+    diff tmp/feed.xml htdocs/feed.xml
+    rc=$?
+fi
+if [ "$rc" = "0" ]; then
+    curl http://localhost:8090/test/111 >tmp/entry.xml 2>/dev/null
+    diff tmp/entry.xml htdocs/entry.xml
+    rc=$?
+fi
+if [ "$rc" = "0" ]; then
+    curl http://localhost:8090/test/ -X POST -H "Content-type: application/atom+xml" --data @htdocs/entry.xml 2>/dev/null
+    rc=$?
+fi
+if [ "$rc" = "0" ]; then
+    curl http://localhost:8090/test/111 -X PUT -H "Content-type: application/atom+xml" --data @htdocs/entry.xml 2>/dev/null
+    rc=$?
+fi
+if [ "$rc" = "0" ]; then
+    curl http://localhost:8090/test/111 -X DELETE 2>/dev/null
+    rc=$?
+fi
+
+# Test JSON-RPC
+if [ "$rc" = "0" ]; then
+    curl http://localhost:8090/test/ -X POST -H "Content-type: application/json-rpc" --data @htdocs/json-request.txt >tmp/json-result.txt 2>/dev/null
+    diff tmp/json-result.txt htdocs/json-result.txt
+    rc=$?
+fi
+
+# Cleanup
 apachectl -k stop -d `pwd`/tmp
+sleep 1
 if [ "$rc" = "0" ]; then
     echo "OK"
 fi
diff --git a/test/store-script/store-http-test b/test/store-script/store-http-test
--- a/test/store-script/store-http-test
+++ b/test/store-script/store-http-test
@@ -1,3 +1,5 @@
+#!/bin/sh
+
 #  Licensed to the Apache Software Foundation (ASF) under one
 #  or more contributor license agreements.  See the NOTICE file
 #  distributed with this work for additional information
@@ -15,5 +17,44 @@
 #  specific language governing permissions and limitations
 #  under the License.
 
-SUBDIRS = atom cache eval http json
+echo "Testing..."
 
+# Setup
+../../modules/http/httpd-conf tmp 8092 htdocs
+cat >>tmp/conf/httpd.conf <<EOF
+<Location /Catalog>
+SetHandler mod_tuscany
+SCAContribution `pwd`/
+SCAComponent store
+SCAImplementation store.scm
+</Location>
+
+<Location /Total>
+SetHandler mod_tuscany
+SCAContribution `pwd`/
+SCAComponent store
+SCAImplementation store.scm
+</Location>
+
+<Location /ShoppingCart>
+SetHandler mod_tuscany
+SCAContribution `pwd`/
+SCAComponent store
+SCAImplementation store.scm
+</Location>
+EOF
+apachectl -k start -d `pwd`/tmp
+sleep 1
+
+# Test HTTP GET
+curl http://localhost:8092/store.html 2>/dev/null >tmp/store.html
+diff tmp/store.html htdocs/store.html
+rc=$?
+
+# Cleanup
+apachectl -k stop -d `pwd`/tmp
+sleep 1
+if [ "$rc" = "0" ]; then
+    echo "OK"
+fi
+return $rc
